### ISSUE TITLE
Requiring Perl 5.28

### ISSUE THREAD

**Issue by Grinnz** [hailo/hailo#3]
I'm not sure if you got my comments on this commit since they were not on the version in your repo: https://github.com/hailo/hailo/commit/bb148dddf8503e66924bbd9fe46609735670d511

Bumping the Perl requirement to 5.28 seems very unnecessary and makes the distribution unusable for many people. Unlike module versions one often cannot just upgrade Perl. The previous requirement of 5.10 is common on CPAN, and 5.14 is also reasonable for a more specialized distribution like this.

**Comment by avar** [comment]
You're right. This was some spontaneous idiocy on my part. I've now pushed out another release where it's back to 5.010 and without the aggressive CPAN module pinning. All but the ones where I actually know about incompatibilities with are at "0".
